'use client'
import Head from "next/head";
import Modal from 'react-modal';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { FaTimes } from "react-icons/fa";
import { GrInProgress } from "react-icons/gr";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import sudoku from "../public/sudoku.png";
import Image from "next/image";

import headshot from '../public/headshot.png';




export default function Home() {
    const [darkMode, setDarkMode] = useState(true);

    const [isModalOpen, setIsModalOpen] = useState(false);

    const openModal = () => {
        console.log('model opening');
        setIsModalOpen(true);
    };

    const closeModal = () => {
        console.log('model closing');
        setIsModalOpen(false);
    };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <button className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8 fixed bottom-10 right-10" onClick={openModal}>Contact me!</button>
                
                <Modal
                  isOpen={isModalOpen}
                  onRequestClose={closeModal}
                  className="modal"
                  overlayClassName="overlay"
>
                  <ul className="text- py-0 flex items-center justify-between relative">
                    <h2 className="text-2xl pr-10 pb-2"><strong>Contact Information</strong></h2>
                    <FaTimes
                      onClick={closeModal}
                      className="text-2xl cursor-pointer bg-cyan-500 rounded-md absolute top-0 right-0"
                      style={{
                        transform: 'translate(-10%, -10%)', // Fine-tunes position
                        padding: '4px',
                      }}
                    />
                  </ul>
    
    <p className="py-1 text-xl">+1 (401) 239-9654</p>
    <a className="text-cyan-500 text-xl" href="mailto:carlosn.jak@northeastern.edu">carlson.jak@northeastern.edu</a>
</Modal>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Jake Carlson
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Hi! I&apos;m a Computer Science and Physics student at Northeastern University. Get in touch and let&apos;s work together!
            </p>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-10 md:h-96 md:w-96">
              <Image src={headshot} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I&apos;m graduating in May 2025 with a BS in Computer Science and Physics. I have always been interested 
            in my STEM coursework, but when I began coding in high school for class and the 
            robotics team, I realized that I wanted to pursue computer science for its problem 
            solving nature. I study physics out of intellectual curiosity and wanting to better 
            understand our universe. Once I was comfortable coding, I began doing <a className="text-cyan-500" href="#projects">projects </a> 
            for fun and always with the intention of learning something new. Most notably, I am 
            proud of an iOS app I made that can scan and solve sudoku puzzles using your phone&apos;s 
            camera. This experience taught me that I could learn new (programming) languages on 
            my own and break down a massive idea into achievable milestones. </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"> I co-oped at <a className="text-cyan-500" href="https://www.montai.com/"> Montai Health </a>
            doing machine learning engineering for drug discovery. During my time there, 
            I became interested in the powerful applications of machine learning as well as 
            the highly technical algorithms used in the process itself which I am studying
            further while at Northeastern. Beyond Northeastern, I hope to be 
            in a position where I can use my natural curiosity as an asset and work to solve a wide 
            variety of engaging problems.
            </p>
          </div>
          </section>
          <section id="projects">
          <h3 className="text-3xl py-2 dark:text-white ">Projects</h3>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2  ">
                Sudoku Scan & Solve
              </h3>
              <Image src={sudoku} width={1000} height={100} />
              
              <p className="py-2 text-left">
                • Developed UI for scanning sudoku boards from camera and allowing users to play or
                see solutions to sudoku puzzles
                </p>
                <p className="py-2 text-left">
                • Built a Convolutional Neural Network to detect digits
                </p>
                <p className="py-2 text-left">
                • Utilized Apple&apos;s border detection API to perspective transform the input image and break it up into smaller
                images to feed into the neural network
                </p>
                <p className="py-2 text-left">
                • Designed a backtracking algorithm to solve inputed sudoku puzzles for the user
              </p>
              <h4 className="py-4 text-teal-600">Tools I Used</h4>
              <p className="text-gray-800 py-1">SwiftUI</p>
              <p className="text-gray-800 py-1">TensorFlow</p>
              <p className="text-gray-800 py-1">Python</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 justify-between">
              <GrInProgress className="text-7xl"/>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Who&apos;s Got Next Mobile App (in progress)
              </h3>
              <p className="py-2 text-left">
                • Leading a team to create a convenient UI using for users 
                to enter into a queue to play a game, and be notified when it is their 
                turn to play.
                </p>
                <p className="py-2 text-left">
                • Utilizing Firebase in order to send notifications with cloud messaging 
                and store user login information
              </p>
              <h4 className="py-4 text-teal-600">Tools I Used</h4>
              <p className="text-gray-800 py-1">React Native</p>
              <p className="text-gray-800 py-1">Firebase</p>
              <p className="text-gray-800 py-1">JavaScript</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Image Processor</h3>
              <p className="py-2 text-left">
                • Designed an image processing application using Java Swing with 10+ image operations
              </p>
              <p className="py-2 text-left">
                • Collaborated with a partner while learning the MVC architecture in larger scale programs
              </p>
              <p className="py-2 text-left">
                • Optimized extensibility of code using the command design pattern for grayscale and matrix based blurring
operations like Gaussian Blur
              </p>
              <h4 className="py-4 text-teal-600">Tools I Used</h4>
              <p className="text-gray-800 py-1">Java Swing</p>
              <p className="text-gray-800 py-1">MVC architecture</p>
              <p className="text-gray-800 py-1">OOP Patterns</p>
            </div>
          </div>
        </section>
       
      </main>
    </div>
  );
}